nosana:
  description: Nosana Go Template
global:
  image: registry.hub.docker.com/library/golang:latest
  trigger:
    branch:
      - main
  environment:
    APP_ENV: devnet
jobs:

  - name: install deps and build container
    commands:
      - git clone https://github.com/go-training/helloworld .
      - go run main.go
      - go build main.go 
      - ls -lah
    artifacts:
      - name: build
        path: ./main
        
  - name: release
    commands:
      - ls -lah
      - ./main
    resources:
      - name: build
        path: ./