global:
  image: denoland/deno:latest

  trigger:
    branch:
      - main

jobs:
  - name: install
    commands:
      - deno init
      - deno run main.ts
      - deno test
      - deno bench
      - deno compile main.ts

  - name: say
    commands:
      - deno run --allow-env --allow-read npm:cowsay@1.5.0/cowthink Nosana is Fire!