nosana:
  description: Nosana Python Template

global:
  image: registry.hub.docker.com/library/python:latest

  trigger:
    branch:
      - main

jobs:
  - name: install deps and build container
    commands:
      # Initialize
      - python -m venv count
      - . count/bin/activate
      - pip install numpy flake8 pytest
      - pip freeze > requirements.txt
    artifacts:
      - name: count
        path: count/

  - name: test
    commands:
      - . count/bin/activate
      - pip install -r requirements.txt
      - pytest -v --cov=count/
    resources:
      - name: count
        path: ./
