nosana:
  description: Nosana Go Template
      
global:
  image: registry.hub.docker.com/library/golang:latest

  trigger:
    branch:
      - main

  environment:
    APP_ENV: devnet

jobs:
  - name: install deps and build container
    commands:
      - go mod init example/hello # Initialize
      - touch hello.go
      - echo 'package main' >> hello.go
      - echo 'import "fmt"' >> hello.go
      - echo 'func main() { fmt.Println("Hello, World!") }' >> hello.go
      - echo >> hello.go
      - cat hello.go
      - go run hello.go
      - mkdir build
      - go build -o build/
    artifacts:
      - name: build
        path: ./build/

  - name: release
    commands:
      - ./build/hello
    resources:
      - name: build
        path: ./
