nosana:
  description: Nosana-Node Pipeline
      
global:
  image: registry.hub.docker.com/library/ubuntu:latest

  trigger:
    branch:
      - all
      
  environment:
    FIZZ: BUZZ

jobs:
  - name: Create README
    commands:
      - export FOO=BAR
      - echo $FOO
      - mkdir test
      - touch test/README.md
      - echo "Hello, World!" >> test/README.md
    artifacts:
      - name: test
        path: test/

  - name: Print README
    commands:
      - cat ./test/README.md
      - echo $FIZZ
      - echo $ALICE
    environment:
      ALICE: BOB
    resources:
      - name: test
        path: ./
