nosana:
  description: Nosana Go Template
      
global:
  image: registry.hub.docker.com/library/golang:latest

  trigger:
    branch:
      - main

  environment:
    APP_ENV: devnet

jobs:
  - name: install deps and build container
    commands:
      - git clone https://github.com/go-training/helloworld 
      - cd helloworld
      - go run main.go
      - mkdir build/
      - go build main.go -o build
    artifacts:
      - name: build
        path: ./

  - name: release
    commands:
      - ./build/main
    resources:
      - name: build
        path: ./
